# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            .thoughts
tagline:          ''
description:      'A collection of stories, experiences, adventures and misadventures, from the landscapes of Southeast Asia to the trenches of programming and ops.'
url:              http://vincentpaca.com
baseurl:          /

author:
  name:           'Vincent Paca'
  url:            https://vincentpaca.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/vincentpaca
